apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-210218-fkmu-service
spec:
  selector:
    app: enterprise-system-210218-fkmu
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
